#!/bin/bash
#purpose of this file: create a tmux session at a specific directory depending on user input
#Date: 2021-05-29
#---------------------------------

shopt -s expand_aliases
source ~/.bash_aliases

read -p "What class will this be? (1.OOP, 2.SYD, 3.CUL) " CLASS

case $CLASS in
	"OOP"|"1")
	{
		read -p "which workshop? (1-9): " WORKSHOPNUMBER
		read -p "part 1 or 2? " WORKSHOPPART
		cdoop
		SESSION_NAME="oop_ws$WORKSHOPNUMBER"
		tmux new-session -d -s $SESSION_NAME
		tmux rename-window -t 0 'code'
		tmux send-keys -t 0 cdoop Enter
		if [[ -z $WORKSHOPPART ]]; then
			tmux send-keys -t 0 "cd workshops/ws_$WORKSHOPNUMBER" Enter
		else
			tmux send-keys -t 0 "cd workshops/ws_$WORKSHOPNUMBER/part_$WORKSHOPPART" Enter
		fi
		tmux send-keys -t 0 "clear" Enter
		tmux new-window -t $SESSION_NAME:1 -n 'notes'
		tmux send-keys -t 'notes' oopnotes Enter
		tmux attach-session -t $SESSION_NAME:0
	};;

	"SYD"|"2")
	{
		#echo SYD
		read -p "1.lab or 2.week: " DEST

		if [[ $DEST == "1" || $DEST == "lab" ]]; then
			cdsyd
			tmux new-session -d -s syd_lab
			tmux send-keys -t 0 cdsyd Enter
			tmux send-keys -t 0 "cd labs" Enter
			tmux send-keys -t 0 "clear" Enter
			tmux attach-session -t syd_lab
		elif [[ $DEST == "2" || $DEST == "week" ]]; then
			cdsyd
			read -p "which week? (1-13) week_" WEEKNUMBER
			tmux new-session -d -s syd_weekly_notes
			tmux send-keys -t 0 cdsyd Enter
			tmux send-keys -t 0 "cd week_$WEEKNUMBER" Enter
			tmux send-keys -t 0 "clear" Enter
			tmux attach-session -t syd_weekly_notes
		fi

	};;

	"CUL"|"3")
	{
		#echo CUL
		read -p "which week? (1-13). For essay, enter 14 or essay. week_" WEEKNUMBERCUL
		if [[ "$WEEKNUMBERCUL" == "14" || "$WEEKNUMBERCUL" == "essay" ]]; then
			cdcul
			tmux new-session -d -s cul_essay
			tmux send-keys -t 0 cdcul Enter
			tmux send-keys -t 0 "cd essay" Enter
			tmux send-keys -t 0 "vim -c \":tab all\" essay.md outline.md" Enter
			tmux attach-session -t cul_essay
		else
			cdcul
			tmux new-session -d -s cul_weekly
			tmux send-keys -t 0 cdcul Enter
			tmux send-keys -t 0 "cd week_$WEEKNUMBER" Enter
			tmux send-keys -t 0 "clear" Enter
			tmux attach-session -t cul_weekly
		fi

	};;
esac


