#!/bin/bash
# task calendar
cal

MONTH=$(date +%b)

if [[ -z $1 ]]; then
   read -p "task name: " NAME
else
   NAME="$@"
fi

read -p "due date: $MONTH " DATE

CLASS=$(echo -e "C#\nBCI\nJAC\nPRJ\n" | fzf)

ultralist add $NAME due:${DATE}${MONTH} +$CLASS

# task add "${NAME}" project:$CLASS\
   # due:$YEAR-$MONTH-$DATE \
   # +seneca

# task
ultralist list
