#!/bin/bash
#purpose of this file: add a task to project seneca with due date
#Date: 2021-05-16 
#---------------------------------

task calendar

if [[ -z $1 ]]; then
   read -p "task name: " NAME
else
   NAME="$@"
fi

read -p "due date: " DATE
select CLASS in JAC WEB SYD EAC
do
   task add "${NAME}" project:$CLASS\
      due:$DATE \
      +seneca
   task  # then display all tasks
   exit
done
