#!/bin/bash
#purpose of this file: add a task to project seneca with due date
#Date: 2021-05-16 
#---------------------------------


#context:school
#project: class name or lecture
#tags: for each class
task calendar

if [[ -z $1 ]]; then
	read -p "task name: " NAME
else
	NAME="$1"
fi

read -p "due date: " DATE
read -p "class name (1.OOP 2.CUL 3.SYD): " CLASS

if [[ $CLASS == "1" || $CLASS == "OOP" || $CLASS == "oop" ]]; then
	CLASS="OOP"

elif [[ $CLASS == "2" || $CLASS == "CUL" || $CLASS == "cul" ]]; then
	CLASS="CUL"

elif [[ $CLASS == "3" || $CLASS == "SYD" || $CLASS == "syd" ]]; then
	CLASS="SYD"
fi

task add "${NAME}" project:$CLASS\
	due:$DATE \
	+seneca

task context school

task
