vim.keymap.set("i", "<C-s>", function()
	vim.fn["UltiSnips#ExpandSnippetOrJump"]()
end, { silent = true })
vim.keymap.set("v", "<C-s>", function()
	vim.fn["UltiSnips#ExpandSnippetOrJump"]()
end, { silent = true })
