---
- hosts: localhost
  become: true
  tasks:
     - name: install go
       import_role:
          name: gantsign.golang
       become: true
       vars:
          golang_version: "1.19.4"
     - name: install gopls
       ansible.builtin.command:
          cmd: go install golang.org/x/tools/gopls@latest
     - name: install bash language server
       ignore_errors: true
       ansible.builtin.package:
          name: bash-language-server
