---
- name: sync nvim config
  hosts: localhost
  become: false
  vars:
     branches:
        - windows
        - work_laptop
  tasks:
     - name: loop over branches
       shell: "echo {{ item }}"
       loop: "{{ branches }}"

     - name: sync neovim config in windows branch
       shell: |
          cd ~/personal
          git checkout main
          git pull
          git checkout {{ item }}
          git checkout main .config/nvim
          git add .config/nvim
          git commit -m "merged nvim config from main"
          git push
       loop: "{{ branches }}"
