- name: |
    Sync tasks]
    [Description: sync tasks from current branch to other branches that requires the tasks
  hosts: localhost
  become: false
  vars:
     branch:
        - main
        - windows
        - new_pc
  tasks:
     - name: get current branch name
       register: branch_name_command
       shell: git rev-parse --abbrev-ref HEAD

     - set_fact:
          # branch to sync info to
          target_branch: "{{ branch | difference(branch_name_command.stdout) }}"
          # current branch
          og_branch: "{{ branch | intersect(branch_name_command.stdout) }}"

     #- debug:
         #msg: "target branch {{ target_branch }}"
     #- debug:
         #msg: "og_branch {{ og_branch }}"
     - name: "sync task from {{ target_branch[0] }} branch"
       register: sync_tasks
       shell: |
          cd ~/personal
          git fetch --all
          git pull --all
          git worktree add {{ target_branch[0] }} {{ target_branch[0] }}
          cd {{ target_branch[0] }}
          git pull
          git checkout {{ og_branch[0] }} .task
          git add .task
          git commit -m "synced .task from branch {{ og_branch[0] }}"
          git push
          cd ..
          git worktree remove {{ target_branch[0] }}
     - name: stdout
       debug:
          msg: "{{ sync_tasks.stdout_lines }}"
     # - name: stderr
       # debug:
          # msg: "{{ sync_tasks.stderr.split('\n') }}"
