---
- name: sync nvim config
  hosts: localhost
  become: false
  vars:
     branches:
        - main
        - windows
        - work_laptop

  tasks:
     - name: get current branch name
       register: branch_name_command
       shell: git rev-parse --abbrev-ref HEAD

     - set_fact:
          # branch to sync info to
          target_branches:
             "{{ branches | difference(branch_name_command.stdout) }}"
             # current branch
          og_branch: "{{ branches | intersect(branch_name_command.stdout) }}"

     - name: "sync nvim config"
       register: sync_config
       shell: |
          cd ~/personal/
          echo "syncing {{ item }} branch"
          git worktree add {{ item }}
          cd {{ item }}
          git pull
          git checkout {{ og_branch[0] }} .config/nvim
          git commit -m "merged neovim config from {{ og_branch[0] }}"
          git push
          cd ..
          git worktree remove {{ item }}
       loop: "{{ target_branches }}"

     - name: stdout
       debug:
          msg: "{{ item.stdout_lines}}"
       loop: "{{ sync_config.results }}"
