- name: sync ultratasks
  hosts: localhost
  become: false
  vars:
    branch:
      - main
      - windows
  tasks:
    - name: get current branch name
      register: branch_name_command
      shell: git rev-parse --abbrev-ref HEAD

    - set_fact:
        # branch to sync info from
        target_branch: "{{ branch | difference(branch_name_command.stdout) }}"
        # current branch
        og_branch: "{{ branch | intersect(branch_name_command.stdout) }}"

    # - name: debug
      # debug:
        # msg: "{{ branch | intersect(branch_name_command.stdout) }}"
    - name: "sync task from {{ target_branch }} branch"
      register: sync_task
      shell: |
        git checkout {{ target_branch[0] }}
        git pull
        git checkout {{ og_branch[0] }}
        git pull
        git checkout {{ target_branch[0] }} .todos.json
        # git add .todos.json
        # git commit -m "synced .todos.json from branch {{ target_branch[0] }}"
        # git push
    - debug:
        msg: "{{ sync_task.stdout }}"
