- name: sync ultratasks
  hosts: localhost
  become: false
  tasks:
    - name: sync task from windows branch
      shell: |
        git checkout windows
        git pull
        git checkout main
        git pull
        git checkout windows .todos.json
        git add .todos.json
        git commit -m "synced .todos.json from branch windows"
        git push


