#  _______| |__  _ __ ___ 
# |_  / __| '_ \| '__/ __|
#  / /\__ \ | | | | | (__ 
# /___|___/_| |_|_|  \___|

# Set up the prompt

#autoload -Uz promptinit
#promptinit
#prompt adam1

setopt histignorealldups sharehistory

#allow for piping to /dev/null
unsetopt multios

#export TERM="screen-256color"

fpath=(~/personal/custom_completion $fpath)

# allow auto completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# Enable colors and change prompt:
autoload -U colors && colors

export TERM="xterm-256color"

precmd_functions=""

#luke smith ranbow colours
# PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '🎄 %b'
precmd() { vcs_info }
# Enable substitution in the prompt.
setopt prompt_subst


# NOTE: prompt must be wrapped in single quotes for the git stuff to work
PROMPT='%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}] %{$fg[green]%}⛏  %j%E %{$fg[cyan]%}${vcs_info_msg_0_}
%{$fg[cyan]%}$%{$reset_color%}%b '



# PS1="%M%n"

#zsh prompt script
#source /home/shawn/personal/zsh_config/prompt_adam1_setup.zsh

#orginal
#PROMPT="%K{blue}%n@%m%k %B%F{cyan}%(4~|...|)%3~%F{white} %# %b%f%k"

#PROMPT='%~ $# '
#PS1='%F{blue}%1~%f %# '


# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

function cd_with_fzf
{
    cd "$(find ~ -type d \( -name "*" ! -iname ".*" \) | fzf --bind="space:toggle-preview")" && pwd && ls --group-directories-first --color=auto
}
#create a witget using function above
zle -N cd_with_fzf
#bind control f to witget
bindkey '^F' cd_with_fzf

#if remaps.sh exists, call it
if [[ -f ~/remaps.sh ]]; then
    . ~/remaps.sh
fi

if [[ -f ~/.fzf.zsh ]]; then
    source ~/.fzf.zsh
fi

SENECA_MATRIX='hyu126@matrix.senecacollege.ca'

export IGNOREEOF=10

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#setting default editor to neovim 
export EDITOR='nvim'
export VISUAL="$EDITOR"

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

#load alias file
if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

if [ -f ~/.zsh_aliases-custom ]; then
    . ~/.zsh_aliases-custom
fi

export PATH="$PATH:/home/shawn/scripts/template-file-creation"
export PATH="$PATH:/home/shawn/personal/task_worrior/:/home/shawn/scripts/for_path/vpn_launcher/:$HOME/scripts/in_path/"
export PATH="$PATH:/opt/mssql-tools/bin"
export PATH="$PATH:/usr/local/bin/java-language-server/dist/linux/bin/"
export JDTLS_HOME=/usr/local/bin/jdt

## Enable substitution in the prompt.
#setopt prompt_subst

# Config for prompt. PS1 synonym.
#prompt='%2/ $(git_branch_name) > '

#syntax highlighting. MUST BE ON THE BOTTOM OF THE FILE
#source /home/shawn/personal/zsh_config/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


#auto suggestions
source /home/shawn/personal/linux_config/zsh_config/zsh-autosuggestions/zsh-autosuggestions.zsh

# Change cursor shape for different vi modes.
#function zle-keymap-select {
  #if [[ ${KEYMAP} == vicmd ]] ||
     #[[ $1 = 'block' ]]; then
    #echo -ne '\e[1 q'
  #elif [[ ${KEYMAP} == main ]] ||
       #[[ ${KEYMAP} == viins ]] ||
       #[[ ${KEYMAP} = '' ]] ||
       #[[ $1 = 'beam' ]]; then
    #echo -ne '\e[5 q'
  #fi
#}
#zle -N zle-keymap-select
#zle-line-init() {
    #zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    #echo -ne "\e[5 q"
#}
#zle -N zle-line-init
#echo -ne '\e[5 q' # Use beam shape cursor on startup.
#preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
## Find and set branch name var if in git repository.
#function git_branch_name()
#{
  #branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  #if [[ $branch == "" ]];
  #then
    #:
  #else
    #echo '- ('$branch')'
  #fi
#}


alias luamake=/home/shawn/lua-language-server/3rd/luamake/luamake
