---
- name: install git
  become: true
  package:
    name: git
    state: latest

- name: copy git-credentials
  copy:
    src: "{{ personal_dir }}/.git-credentials"
    dest: "{{ansible_env.HOME }}/.git-credentials"
