---
- name: install git
  become: true
  package:
    name: git
    state: latest

- name: link git-credentials
  copy:
    src: "{{ personal_dir }}/.git-credentials"
    dest: "{{ ansible_env.HOME }}/.git-credentials"

- name: Set name and email address
  shell: |
      git config --global user.email "shawn.yu5@hotmail.com"
      git config --global user.name "Shawn Yu"

