---
- name: install git
  become: true
  ignore_errors: true
  register: git
  package:
    name:
      - git
      - git-delta
      - github-cli
    state: latest

- name: install git delta using cargo
  ignore_errors: true
  when: git.rc == 1
  shell: cargo install git-delta

- name: install gh cli plugins
  ignore_errors: true
  shell: |
    gh extension install https://github.com/mislav/gh-branch
    gh extension install https://github.com/shawnyu5/gh-ac
    gh extension install https://github.com/seachicken/gh-poi

- name: copy git-credentials
  copy:
    src: "{{ personal_dir }}/.git-credentials"
    dest: "{{ ansible_env.HOME }}/.git-credentials"

- name: copy gitconfig
  copy:
    src: "{{ personal_dir }}/.gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
