---
- name: Install flameshot (screen shot tool)
  tags:
    - i3
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: flameshot
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Install kitty
  tags:
    - i3
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name:
      - kitty
      - picom
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Link kitty config
  tags:
    - i3
  when: system_name == 'linux'
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/kitty"
    dest: "{{ ansible_env.HOME }}/.config/kitty"
    state: link
    force: true

- name: Link i3 config
  tags:
    - i3
  when: system_name == 'linux'
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/i3"
    dest: "{{ ansible_env.HOME }}/.config/i3"
    state: link
    force: true

- name: Link i3blocks config
  tags:
    - i3
  when: system_name == 'linux'
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/i3blocks"
    dest: "{{ ansible_env.HOME }}/.config/i3blocks"
    state: link
    force: true

- name: Link picom config
  tags:
    - i3
  when: system_name == 'linux'
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/picom"
    dest: "{{ ansible_env.HOME }}/.config/picom"
    state: link
    force: true

- name: Link rofi config
  tags:
    - i3
  when: system_name == 'linux'
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/rofi"
    dest: "{{ ansible_env.HOME }}/.config/rofi"
    state: link
    force: true

- name: Setup screen layout
  tags:
    - i3
  when: system_name == "linux"
  ansible.builtin.file:
    src: "{{ personal_dir }}/screenlayout"
    dest: "{{ ansible_env.HOME }}/.screenlayout"
    state: link
    force: true

- name: Setup systemctl service to disable USB wakeup
  become: true
  tags:
    - i3
  ansible.builtin.file:
    src: "{{ personal_dir }}/disable-usb-wakeup.service"
    dest: "/etc/systemd/system/disable-usb-wakeup.service"
    state: link
    # force: true

- name: Enable disable USB wakeup service
  tags:
    - i3
  become: true
  ansible.builtin.systemd_service:
    name: disable-usb-wakeup.service
    enabled: true
    state: "started"
