---
- name: Install additional packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Set up neovim
  ansible.builtin.include_tasks:
    file: neovim.yml

- name: Setup ranger
  ansible.builtin.include_tasks:
    file: ranger.yml

- name: Set up ZSH
  ansible.builtin.include_tasks:
    file: zsh.yml

- name: Set up tmux
  ansible.builtin.include_tasks:
    file: tmux.yml

- name: Install i3
  ansible.builtin.include_tasks:
    file: i3.yml

- name: Set up git
  ansible.builtin.include_tasks:
    file: git.yml
- name: Set up task worrior
  ansible.builtin.include_tasks:
    file: task_worrior.yml

- name: Set up bacon
  ansible.builtin.include_tasks:
    file: bacon.yml
