---
- name: Load system_config.json
  tags:
    - always
  ansible.builtin.set_fact:
    system_config: "{{ lookup('file', '%s/system_config.json' | format(personal_dir)) | from_json }}"

- name: Set system name
  tags:
    - always
  ansible.builtin.set_fact:
    system_name: "{{ system_config.system_name }}"

- name: Install additional packages
  ansible.builtin.import_tasks:
    file: packages.yml

- name: Set up neovim
  tags:
    - neovim
  ansible.builtin.import_tasks:
    file: neovim.yml

- name: Setup ranger
  ansible.builtin.import_tasks:
    file: ranger.yml

- name: Set up ZSH
  tags:
    - zsh
  ansible.builtin.import_tasks:
    file: zsh.yml

- name: Set up tmux
  tags: tmux
  ansible.builtin.import_tasks:
    file: tmux.yml

- name: Install i3
  when: system_name == 'linux'
  tags:
    - i3
  ansible.builtin.import_tasks:
    file: i3.yml

- name: Set up git
  tags:
    - git
  ansible.builtin.import_tasks:
    file: git.yml

- name: Set up bacon
  ansible.builtin.import_tasks:
    file: bacon.yml
