---
- name: set up neovim
  include_tasks:
    file: neovim.yml
- name: set up ZSH
  include_tasks:
    file: zsh.yml
- name: set up tmux
  include_tasks:
    file: tmux.yml
- name: install i3 dependencies
  include_tasks:
    file: i3.yml
- name: set up git
  include_tasks:
    file: git.yml
