---
- name: install neovim
  ignore_errors: true
  become: true
  package:
    name: neovim
    state: latest

- name: install gcc
  become: true
  package:
    name: gcc
    state: latest

- name: install unzip
  become: true
  package:
    name: unzip
    state: latest

- name: install node
  become: true
  package:
    name: nodejs
    state: latest

- name: install pynvim
  become: true
  ignore_errors: true
  package:
    name: python-pynvim
    state: latest

- name: install ripgrep
  ignore_errors: true
  become: true
  package:
    name: ripgrep
    state: latest

- name: install xclip
  become: true
  package:
    name: xclip
    state: latest

- name: create .config directory
  ignore_errors: true
  file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory
    mode: "0755"

- name: link neovim config
  ignore_errors: true
  file:
    src: "{{ personal_dir }}/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: true

- name: link clang-format config
  ignore_errors: true
  file:
    src: "{{ personal_dir }}/.clang-format"
    dest: "{{ ansible_env.HOME }}"
    state: link
    force: true
