---
- name: install neovim
  ignore_errors: true
  become: true
  package:
    name: neovim
    state: latest

- name: install gcc
  become: true
  package:
    name: gcc
    state: latest

- name: install node
  become: true
  package:
    name: nodejs
    state: latest

- name: install pip
  become: true
  package:
    name: python3-pip
    state: latest

- name: install pynvim
  become: true
  ignore_errors: true
  shell: pip3 install pynvim

- name: install ripgrep
  ignore_errors: true
  become: true
  package:
    name: ripgrep
    state: latest

- name: install xclip
  become: true
  package:
    name: xclip
    state: latest

- name: create .config directory
  ignore_errors: true
  file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory
    mode: '0755'

- name: link neovim config
  file:
    src: "{{ personal_dir }}/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
