---
- name: install neovim
  ignore_errors: true
  become: true
  package:
    name: neovim
    state: latest
- name: install gcc
  package:
    name: gcc
    state: latest

- name: create .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory
    mode: '0755'

- name: link neovim config
  file:
    src: "{{ ansible_env.HOME }}/personal/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
