---
# We only install neovim nightly on arch. This failing on other system is fine
# On non arch systems, we can manually build from source
- name: Install neovim
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: neovim-nightly-bin
    state: latest

- name: Install gcc
  become: true
  ansible.builtin.package:
    name: gcc
    state: latest

- name: Install unzip
  become: true
  ansible.builtin.package:
    name: unzip
    state: latest

# For telescope fzf native finder
- name: Install cmake
  become: true
  ansible.builtin.package:
    name: cmake
    state: latest

# Only coc used to depend on node. That is no longer the case.
# - name: Install node
#   become: true
#   ansible.builtin.package:
#     name: nodejs
#     state: latest

- name: Install pynvim
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: python-pynvim
    state: latest

- name: Install ripgrep
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: ripgrep
    state: latest

- name: Install xclip
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: xclip
    state: latest

- name: Create .config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory
    mode: "0755"

- name: Link neovim config
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: true

- name: Link clang-format config
  ansible.builtin.file:
    src: "{{ personal_dir }}/.clang-format"
    dest: "{{ ansible_env.HOME }}/.clang-format"
    state: link
    force: true
