---
- name: Install emojies
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: noto-fonts-emoji
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Install less
  become: true
  ansible.builtin.package:
    name: less
    state: latest

- name: Install discord
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: discord
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Install bat
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: bat
    state: "latest"

- name: Install rustup using package manager
  tags:
    - zsh
    - neovim
  ignore_errors: true
  become: true
  register: rustup_install
  ansible.builtin.package:
    name: rustup
    state: latest

- name: Install rustup using install script
  tags:
    - zsh
    - neovim
  become: true
  ignore_errors: true
  changed_when: rustup_install.failed
  ansible.builtin.command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  when: rustup_install.failed

- name: Set default rust
  tags:
    - zsh
    - neovim
  changed_when: true
  ansible.builtin.command: rustup default stable

- name: Install font
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name:
      - ttf-fira-code
      - ttf-firacode-nerd
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Install node and NPM
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: latest

- name: Install go
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: go
    state: latest

- name: Install java
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - jdk21-openjdk
      # NOTE: we should only need to install the JDK
      # - jre21-openjdk
    state: latest

- name: Install htop
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: htop
    state: latest

- name: Install fzf
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: fzf
    state: latest

- name: Install okular PDF viewer
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: okular
    state: "{{ 'latest' if system_name == 'linux' else 'absent' }}"

- name: Install docker
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: latest

- name: Install gdb
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: gdb
    state: latest

- name: Install terraform
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: terraform
    state: latest

- name: Install kubernetes related packages
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - minikube
      - kubectl
      - k9s
    state: latest

# NOTE: we only need to install asdf on work laptop. It will never come from the package manager
# - name: Install asdf using package manager (arch only)
#   become: true
#   ignore_errors: true
#   register: ansible_install
#   ansible.builtin.package:
#     name: asdf
#     state: latest

- name: Check if asdf is installed
  ansible.builtin.command: which asdf
  changed_when: false
  ignore_errors: true
  register: asdf_installed

- name: Install asdf using go
  when: system_name == 'work_laptop' and asdf_installed.failed
  changed_when: system_name == 'work_laptop' and asdf_installed.failed
  ansible.builtin.command: go install github.com/asdf-vm/asdf/cmd/asdf@latest

- name: Link asdf tools config
  when: "system_name == 'work_laptop'"
  ansible.builtin.file:
    src: "{{ personal_dir }}/.tool-versions"
    dest: "{{ ansible_env.HOME }}/.tool-versions"
    state: link
    force: true

- name: Install zoxide using package manager
  register: zoxide_install
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: zoxide
    state: latest

- name: Check if zoxide is installed
  ansible.builtin.command: which zoxide
  changed_when: false
  ignore_errors: true
  register: zoxide_installed

- name: Download zoxide install script
  when: zoxide_install.failed and  zoxide_installed.failed
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/zoxide_install.sh
    mode: "0755"

- name: Run zoxide install script
  when: zoxide_install.failed and  zoxide_installed.failed
  changed_when: zoxide_install.failed and  zoxide_installed.failed
  ansible.builtin.shell: /tmp/zoxide_install.sh
