---
- name: install emojies
  ignore_errors: true
  become: true
  package:
    name: noto-fonts-emoji
    state: latest

- name: install discord
  ignore_errors: true
  become: true
  package:
    name: discord
    state: latest

- name: install rust
  ignore_errors: true
  become: true
  package:
    name: rust
    state: latest

- name: install font
  ignore_errors: true
  become: true
  package:
    name:
      - ttf-fira-code
      - ttf-firacode-nerd
    state: latest

- name: install node and NPM
  ignore_errors: true
  become: true
  package:
    name:
      - nodejs
      - npm
    state: latest

- name: install go
  ignore_errors: true
  become: true
  package:
    name: go
    state: latest

- name: install ranger
  become: true
  ignore_errors: true
  package:
    name: ranger
    state: latest
