---
- name: Install emojies
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: noto-fonts-emoji
    state: latest

- name: Install less
  become: true
  ansible.builtin.package:
    name: less
    state: latest

- name: Install discord
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: discord
    state: latest

- name: Install rustup using package manager
  ignore_errors: true
  become: true
  register: rustup_install
  ansible.builtin.package:
    name: rustup
    state: latest

- name: Install rustup using install script
  become: true
  ignore_errors: true
  ansible.builtin.command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  when: "rustup_install.failed"

- name: Set default rust
  ignore_errors: true
  ansible.builtin.command: rustup default stable

- name: Install font
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name:
      - ttf-fira-code
      - ttf-firacode-nerd
    state: latest

- name: Install node and NPM
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: latest

- name: Install go
  ignore_errors: true
  become: true
  ansible.builtin.package:
    name: go
    state: latest

- name: Install java
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - jdk21-openjdk
      # NOTE: we should only need to install the JDK
      # - jre21-openjdk
    state: latest

- name: Install htop
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: htop
    state: latest

- name: Install fzf
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: fzf
    state: latest

- name: Install okular PDF viewer
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: okular
    state: latest

- name: Install docker
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: latest

- name: Install gdb
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: gdb
    state: latest

- name: Install terraform
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: terraform
    state: latest

- name: Install kubernetes related packages
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - minikube
      - kubectl
      - k9s
    state: latest

- name: Install asdf using package manager (arch only)
  become: true
  ignore_errors: true
  register: ansible_install
  ansible.builtin.package:
    name: asdf
    state: latest

- name: Install asdf using go
  when: ansible_install.failed
  ansible.builtin.command: go install github.com/asdf-vm/asdf/cmd/asdf@latest

- name: Link asdf tools config
  ansible.builtin.file:
    src: "{{ personal_dir }}/.tool-versions"
    dest: "{{ ansible_env.HOME }}/.tool-versions"
    state: link
    force: true

- name: Install zoxide using package manager
  register: zoxide_install
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name: zoxide
    state: latest

- name: Install zoxide using script
  become: true
  when: zoxide_install.failed
  ansible.builtin.command: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
