---
- name: install emojies
  ignore_errors: true
  become: true
  package:
    name: noto-fonts-emoji
    state: latest

- name: install git-delta
  ignore_errors: true
  become: true
  package:
    name: git-delta
    state: latest

- name: install discord
  ignore_errors: true
  become: true
  package:
    name: discord
    state: latest



