---
- name: Install ranger
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - ranger
      - ueberzug
    state: latest

- name: Link ranger config
  ignore_errors: true
  ansible.builtin.file:
    src: "{{ personal_dir }}/.config/ranger"
    dest: "{{ ansible_env.HOME }}/.config/ranger"
    state: link
    force: true
