---
- name: Install tmux
  become: true
  ignore_errors: true
  ansible.builtin.package:
    name:
      - tmux
      # tmux window-rename dependency
      # - python-libtmux
    state: latest

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/"

- name: Link tmux conf
  ansible.builtin.file:
    src: "{{ personal_dir }}/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link

- name: Clone tmux powerline
  ansible.builtin.git:
    repo: https://github.com/shawnyu5/tmux-powerline
    dest: "{{ ansible_env.HOME }}/.tmux/tmux-powerline/"

- name: Link tmux powerline config
  ansible.builtin.file:
    src: "{{ personal_dir }}/.tmux-powerlinerc"
    dest: "{{ ansible_env.HOME }}/.tmux-powerlinerc"
    state: link
