---
- name: install tmux
  become: true
  package:
    name:
      - tmux
      # tmux window-rename dependency
      - python-libtmux
    state: latest

- name: install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/"

- name: link tmux conf
  file:
    src: "{{ personal_dir }}/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link

- name: clone tmux powerline
  git:
    repo: https://github.com/shawnyu5/tmux-powerline
    dest: "{{ ansible_env.HOME }}/.tmux/tmux-powerline/"

- name: link tmux powerline config
  file:
    src: "{{ personal_dir }}/.tmux-powerlinerc"
    dest: "{{ ansible_env.HOME }}/.tmux-powerlinerc"
    state: link
