---
- name: Install zsh
  become: true
  ansible.builtin.package:
    name:
      - zsh
    state: latest

- name: Install starship
  become: true
  ignore_errors: true
  register: starship
  ansible.builtin.package:
    name: starship
    state: latest

- name: Check if starship is installed
  ansible.builtin.command: which starship
  changed_when: false
  ignore_errors: true
  register: starship_installed

- name: Install starship using cargo
  when: starship.failed
  changed_when: ansible.failed and starship_installed.failed
  ansible.builtin.command: cargo install starship --locked

- name: Link zshrc
  ansible.builtin.file:
    src: "{{ personal_dir }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link

- name: Link zsh_aliases
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases"
    src: "{{ personal_dir }}/.zsh_aliases"
    state: link

- name: Link zsh_aliases_custom
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases-custom"
    src: "{{ personal_dir }}/.zsh_aliases-custom"
    state: link

- name: Link starship config
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    src: "{{ personal_dir }}/.config/starship.toml"
    state: link
    force: true
