---
- name: Install zsh
  become: true
  ignore_errors: true
  register: zsh
  ansible.builtin.package:
    name:
      - zsh
      - starship
    state: latest

- name: Install starship using cargo
  when: zsh.rc | default(0) == 1
  ansible.builtin.command: cargo install starship --locked
- name: Link zshrc
  ansible.builtin.file:
    src: "{{ personal_dir }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link

- name: Link zsh_aliases
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases"
    src: "{{ personal_dir }}/.zsh_aliases"
    state: link

- name: Link zsh_aliases_custom
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases-custom"
    src: "{{ personal_dir }}/.zsh_aliases-custom"
    state: link

- name: Link starship config
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    src: "{{ personal_dir }}/.config/starship.toml"
    state: link
    force: true
# - name: Install zinit
#   shell: |
#     bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
#     zinit self-update
