---
- name: install zsh
  become: true
  ignore_errors: true
  package:
    name:
      - zsh
      - starship
    state: latest

# - name: set default shell
# shell: |
# chsh -s $(which zsh)

- name: link zshrc
  file:
    src: "{{ personal_dir }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link

- name: link zsh_aliases
  file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases"
    src: "{{ personal_dir }}/.zsh_aliases"
    state: link

- name: link zsh_aliases_custom
  file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases-custom"
    src: "{{ personal_dir }}/.zsh_aliases-custom"
    state: link

- name: link starship config
  file:
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    src: "{{ personal_dir }}/.config/starship.toml"
    state: link
    force: true
