---
- name: install zsh
  become: true
  ignore_errors: true
  package:
    name: zsh
    state: latest

- name: set default shell
  shell: |
    chsh -s $(which zsh)

- name: install ranger
  become: true
  ignore_errors: true
  package:
    name: ranger
    state: latest

- name: link zshrc
  file:
    src: "{{ personal_dir }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link

- name: link zsh_aliases
  file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases"
    src: "{{ personal_dir }}/.zsh_aliases"
    state: link

- name: link zsh_aliases_custom
  file:
    dest: "{{ ansible_env.HOME }}/.zsh_aliases-custom"
    src: "{{ personal_dir }}/.zsh_aliases-custom"
    state: link
