name: Hello
on:
  push:
    branches:
      - "**"
jobs:
  hello:
    name: hello
    runs-on:
      - ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo hello world

  hello2:
    name: hello2
    runs-on:
      - ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo hello world
